### ISSUE TITLE
Title the Score and enhance its visual appeal.

### ISSUE THREAD

**Issue by vikram-kangotra** [vikram-kangotra/Dino#2]
At present, the score is displayed solely on the right side without any accompanying label. To enhance clarity, consider incorporating a descriptive label alongside the score. Additionally, make subtle adjustments to enhance the overall visual appeal.

**Comment by chris--jones** [comment]
May I take this one? I was originally looking at the collisions, but I see someone else has asked to look at that one.

**Comment by vikram-kangotra** [comment]
Sure. You can work on this :)
